name: FEDB-CICD
on: [pull_request, workflow_dispatch]
env:
  GIT_SUBMODULE_STRATEGY: recursive
  USER_NAME: dl239
  #PASSWORD: secrets.DL_PAT
jobs:
  fesql_sdk_cpp_sql_sdk_test_level_0:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_fesql:0.0.1-legacy
    steps:
      - uses: actions/checkout@v1
      - name: update nss
        run: yum update -y nss curl libcurl
      - name: set_up
        run: |
          mkdir /rambuild
#          mkdir -p build/bin
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: fesql_sdk_cpp_sql_sdk_test_level_0-report
          path: test/sql_sdk_test.xml

  fesql_sdk_cpp_sql_cluster_test_level_0:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/centos6_gcc7_fesql:0.0.1-legacy
    steps:
      - uses: actions/checkout@v1
      - name: update nss
        run: yum update -y nss curl libcurl
      - name: set_up
        run: |
          mkdir /rambuild
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: fesql_sdk_cpp_sql_cluster_test_level_0-report
          path: test/sql_cluster_test.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: [fesql_sdk_cpp_sql_cluster_test_level_0, fesql_sdk_cpp_sql_sdk_test_level_0]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: fesql_sdk_cpp_sql_sdk_test_level_0-report
          path: reports
      - name: Download Artifacts1
        uses: actions/download-artifact@v1
        with:
          name: fesql_sdk_cpp_sql_cluster_test_level_0-report
          path: reports
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: reports/*.xml
          report_individual_runs: true
          check_run_annotations: all tests, skipped tests

